In [1]:
import pandas as pd

In [27]:
adult = pd.read_csv('raw_data/adult.csv')
adult_simplified = pd.read_csv('anjana_anonymizer/adult-simplified.csv')
adult

,age,workclass,final_weight,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
adult_simplified

,age,workclass,education,marital_status,occupation,relationship,sex,native_country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,Male,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,Male,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,Male,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Male,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Female,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,Female,United-States,<=50K
32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,Male,United-States,>50K
32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,Female,United-States,<=50K
32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,Male,United-States,<=50K
32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,Female,United-States,>50K

In [24]:
adult_over_simplified = adult_simplified.drop(columns=['relationship', 'native_country'])
adult_over_simplified

,age,workclass,education,marital_status,occupation,sex,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Male,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Male,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Male,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Male,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Female,<=50K
...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Female,<=50K
32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Male,>50K
32558,58,Private,HS-grad,Widowed,Adm-clerical,Female,<=50K
32559,22,Private,HS-grad,Never-married,Adm-clerical,Male,<=50K
32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Female,>50K

In [26]:
df_cleaned = adult_over_simplified.replace('?', pd.NA).dropna()
df_cleaned

,age,workclass,education,marital_status,occupation,sex,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Male,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Male,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Male,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Male,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Female,<=50K
...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Female,<=50K
32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Male,>50K
32558,58,Private,HS-grad,Widowed,Adm-clerical,Female,<=50K
32559,22,Private,HS-grad,Never-married,Adm-clerical,Male,<=50K
32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Female,>50K

In [28]:
df_cleaned.to_csv('adult-over-simplified.csv', index=True)